## File: .config/clangd/config.yaml
## License: BSD-3-Clause
CompileFlags:
  Add:
    - "-xc"
    - "-std=c11"
    - "-Wall"
    - "-Wextra"
    - "-Wpedantic"
  Remove:
    - "-x*"
Documentation:
  CommentFormat: Plaintext